Repository whatever-x/mobile, pull requests merged in 2025-01, with the labels that each got.

#9 [Docs] 이슈 템플릿 생성
  .github/ISSUE_TEMPLATE/build.md
  .github/ISSUE_TEMPLATE/discussion.md
  .github/ISSUE_TEMPLATE/docs.md
  .github/ISSUE_TEMPLATE/feature.md
  .github/ISSUE_TEMPLATE/fix.md
  .github/ISSUE_TEMPLATE/hot-fix.md
  .github/ISSUE_TEMPLATE/refactoring.md
Labels: 📚Docs

#11 [Docs] PR 템플릿 생성
  .github/CODEOWNERS
  .github/auto_assign_configs.yml
  .github/pull_request_template.md
  .github/workflows/add-pr-to-project.yml
  .github/workflows/auto-assign.yml
  .github/workflows/update-end-date-on-merge.yml
Labels: ✨Feature, 📚Docs

#8 [INIT] 프로젝트 초기화
  .gitignore
  .kotlin/metadata/kotlinTransformedMetadataLibraries/org.jetbrains.kotlin-kotlin-stdlib-2.0.0-commonMain-2bbUHA.klib
  .kotlin/metadata/kotlinTransformedMetadataLibraries/org.jetbrains.kotlin-kotlin-test-2.0.0-annotationsCommonMain-24eTFQ.klib
  .kotlin/metadata/kotlinTransformedMetadataLibraries/org.jetbrains.kotlin-kotlin-test-2.0.0-assertionsCommonMain-24eTFQ.klib
  androidApp/build.gradle.kts
  androidApp/src/main/AndroidManifest.xml
  androidApp/src/main/java/com/whatever/app/android/MainActivity.kt
  androidApp/src/main/java/com/whatever/app/android/MyApplicationTheme.kt
  androidApp/src/main/res/values/styles.xml
  build.gradle.kts
  common/build.gradle.kts
  common/src/androidMain/kotlin/com/whatever/app/Platform.android.kt
  common/src/commonMain/kotlin/com/whatever/app/Greeting.kt
  common/src/commonMain/kotlin/com/whatever/app/Platform.kt
  common/src/iosMain/kotlin/com/whatever/app/Platform.ios.kt
  composeApp/build.gradle.kts
  composeApp/src/androidMain/AndroidManifest.xml
  composeApp/src/androidMain/kotlin/com/whatever/caramel/GlobalApplication.kt
  composeApp/src/androidMain/kotlin/com/whatever/caramel/MainActivity.kt
  composeApp/src/androidMain/kotlin/com/whatever/caramel/Previews.kt
  composeApp/src/androidMain/kotlin/com/whatever/caramel/di/Modules.android.kt
  composeApp/src/androidMain/res/drawable-v24/ic_launcher_foreground.xml
  composeApp/src/androidMain/res/drawable/ic_launcher_background.xml
  composeApp/src/androidMain/res/mipmap-anydpi-v26/ic_launcher.xml
  composeApp/src/androidMain/res/mipmap-anydpi-v26/ic_launcher_round.xml
  composeApp/src/androidMain/res/mipmap-hdpi/ic_launcher.png
  composeApp/src/androidMain/res/mipmap-hdpi/ic_launcher_round.png
  composeApp/src/androidMain/res/mipmap-mdpi/ic_launcher.png
  composeApp/src/androidMain/res/mipmap-mdpi/ic_launcher_round.png
  composeApp/src/androidMain/res/mipmap-xhdpi/ic_launcher.png
  composeApp/src/androidMain/res/mipmap-xhdpi/ic_launcher_round.png
  composeApp/src/androidMain/res/mipmap-xxhdpi/ic_launcher.png
  composeApp/src/androidMain/res/mipmap-xxhdpi/ic_launcher_round.png
  composeApp/src/androidMain/res/mipmap-xxxhdpi/ic_launcher.png
  composeApp/src/androidMain/res/mipmap-xxxhdpi/ic_launcher_round.png
  composeApp/src/androidMain/res/values/strings.xml
  composeApp/src/commonMain/composeResources/values/strings.xml
  composeApp/src/commonMain/kotlin/com/whatever/caramel/app/App.kt
  composeApp/src/commonMain/kotlin/com/whatever/caramel/core/data/HttpClientExt.kt
  composeApp/src/commonMain/kotlin/com/whatever/caramel/core/data/HttpClientFactory.kt
  composeApp/src/commonMain/kotlin/com/whatever/caramel/core/domain/DataError.kt
  composeApp/src/commonMain/kotlin/com/whatever/caramel/core/domain/Error.kt
  composeApp/src/commonMain/kotlin/com/whatever/caramel/core/domain/Result.kt
  composeApp/src/commonMain/kotlin/com/whatever/caramel/core/presentation/Colors.kt
  composeApp/src/commonMain/kotlin/com/whatever/caramel/core/presentation/DataErrorToStringResource.kt
  composeApp/src/commonMain/kotlin/com/whatever/caramel/core/presentation/UiText.kt
  composeApp/src/commonMain/kotlin/com/whatever/caramel/di/Modules.kt
  composeApp/src/commonMain/kotlin/com/whatever/caramel/di/initKoin.kt
  composeApp/src/iosMain/kotlin/com/whatever/caramel/MainViewController.kt
  composeApp/src/iosMain/kotlin/com/whatever/caramel/di/Modules.ios.kt
  gradle.properties
  gradle/libs.versions.toml
  gradle/wrapper/gradle-wrapper.properties
  iosApp/iosApp/Info.plist
  settings.gradle.kts
Labels: ✨Feature
