Repository whatever-x/mobile, pull requests merged in 2025-07, with the labels that each got.

#223 [QA] 컨텐츠 상세 - 날짜, 시간 UI 추가
  feature/content/detail/src/androidMain/kotlin/com/whatever/caramel/feature/content/detail/ContentDetailPreview.kt
  feature/content/detail/src/commonMain/kotlin/com/whatever/caramel/feature/content/detail/ContentDetailScreen.kt
  feature/content/detail/src/commonMain/kotlin/com/whatever/caramel/feature/content/detail/mvi/ContentDetailState.kt
Labels: ✨Feature

#222 [QA] 홈 - 오늘 일정 리스트 삭제시 아이템이 남아있던 오류 수정
  feature/home/src/commonMain/kotlin/com/whatever/caramel/feature/home/HomeViewModel.kt
Labels: 🛠Fix

#225 [Feat] Pre-Commit Hook 코드 포맷팅 자동화 구현
  .pre-commit-config.yaml
Labels: ✨Feature

#228 [QA] 회원탈퇴 후 토큰을 삭제하도록 변경
  core/domain/src/commonMain/kotlin/com/whatever/caramel/core/domain/usecase/auth/SignOutUseCase.kt
Labels: ✨Feature

#227 [QA] 캘린더 날짜설정이 펴진 후 바텀시트 handling 가능
  feature/calendar/src/commonMain/kotlin/com/whatever/caramel/feature/calendar/CalendarScreen.kt
  feature/calendar/src/commonMain/kotlin/com/whatever/caramel/feature/calendar/CalendarViewModel.kt
  feature/calendar/src/commonMain/kotlin/com/whatever/caramel/feature/calendar/component/bottomSheet/BottomSheetHandle.kt
  feature/calendar/src/commonMain/kotlin/com/whatever/caramel/feature/calendar/mvi/CalendarIntent.kt
  feature/calendar/src/commonMain/kotlin/com/whatever/caramel/feature/calendar/mvi/CalendarState.kt
Labels: 🛠Fix

#230 [QA] 온보딩 UI 오류 수정
  core/designsystem/src/commonMain/composeResources/drawable-hdpi/img_onboarding02.webp
  core/designsystem/src/commonMain/composeResources/drawable-mdpi/img_onboarding02.webp
  core/designsystem/src/commonMain/composeResources/drawable-xhdpi/img_onboarding02.webp
  core/designsystem/src/commonMain/composeResources/drawable-xxhdpi/img_onboarding02.webp
  core/designsystem/src/commonMain/composeResources/drawable-xxxhdpi/img_onboarding02.webp
Labels: 🛠Fix

#231 [QA] 메인 - 홈, 캘린더, 메모 화면 시스템 statusbar 컬러 적용
  feature/calendar/src/commonMain/kotlin/com/whatever/caramel/feature/calendar/CalendarScreen.kt
  feature/home/src/commonMain/kotlin/com/whatever/caramel/feature/home/HomeScreen.kt
  feature/main/src/commonMain/kotlin/com/whatever/caramel/feature/main/MainRoute.kt
  feature/memo/src/commonMain/kotlin/com/whatever/caramel/feature/memo/MemoScreen.kt
Labels: ✨Feature

#234 [Refactor] Slack Notifier 워크 플로우 수정
  .github/workflows/branch-created.yml
  .github/workflows/branch-deleted.yml
  .github/workflows/issue-closed.yml
  .github/workflows/issue-commented.yml
  .github/workflows/issue-opened.yml
  .github/workflows/pr-commented.yml
  .github/workflows/pr-force-closed.yml
  .github/workflows/pr-line-commented.yml
  .github/workflows/pr-merged.yml
  .github/workflows/pr-opened.yml
  .github/workflows/pr-review-submitted.yml
  .github/workflows/push-committed.yml
  .github/workflows/slack-notifier.yml
  .github/workflows/slack_notifier.yml
Labels: 🔃Refactor

#233 [Feat] Crashlytics 로깅 범위 확장
  app-ios/firebaseCrashlyticsBridge/FirebaseCrashlyticsBridge.swift
  app-ios/iosApp/AppDelegate.swift
  app/src/commonMain/kotlin/com/whatever/caramel/app/CaramelViewModel.kt
  app/src/iosMain/kotlin/com/whatever/caramel/di/Module.ios.kt
  core/crashlytics/build.gradle.kts
  core/crashlytics/src/androidMain/kotlin/com/whatever/caramel/core/crashlytics/CaramelCrashlyticsImpl.kt
  core/crashlytics/src/iosMain/kotlin/com/whatever/caramel/core/crashlytics/CaramelCrashlyticsImpl.kt
  core/data/build.gradle.kts
  core/data/src/commonMain/kotlin/com/whatever/caramel/core/data/util/SafeCall.kt
  core/viewmodel/build.gradle.kts
  core/viewmodel/src/commonMain/kotlin/com/whatever/caramel/core/viewmodel/BaseViewModel.kt
  feature/calendar/build.gradle.kts
  feature/calendar/src/commonMain/kotlin/com/whatever/caramel/feature/calendar/CalendarViewModel.kt
  feature/content/create/build.gradle.kts
  feature/content/create/src/commonMain/kotlin/com/whatever/caramel/feature/content/create/ContentCreateViewModel.kt
  feature/content/detail/build.gradle.kts
  feature/content/detail/src/commonMain/kotlin/com/whatever/caramel/feature/content/detail/ContentDetailViewModel.kt
  feature/content/edit/build.gradle.kts
  feature/content/edit/src/commonMain/kotlin/com/whatever/caramel/feature/content/edit/ContentEditViewModel.kt
  feature/couple/connect/build.gradle.kts
  feature/couple/connect/src/commonMain/kotlin/com/whatever/caramel/feature/couple/connect/CoupleConnectViewModel.kt
  feature/couple/connecting/build.gradle.kts
  feature/couple/connecting/src/commonMain/kotlin/com/whatever/caramel/feature/copule/connecting/CoupleConnectingViewModel.kt
  feature/couple/invite/build.gradle.kts
  feature/couple/invite/src/commonMain/kotlin/com/whatever/caramel/feature/copule/invite/CoupleInviteViewModel.kt
  feature/home/build.gradle.kts
  feature/home/src/commonMain/kotlin/com/whatever/caramel/feature/home/HomeViewModel.kt
  feature/login/build.gradle.kts
  feature/login/src/commonMain/kotlin/com/whatever/caramel/feature/login/LoginViewModel.kt
  feature/main/build.gradle.kts
  feature/main/src/commonMain/kotlin/com/whatever/caramel/feature/main/MainViewModel.kt
  feature/memo/build.gradle.kts
  feature/memo/src/commonMain/kotlin/com/whatever/caramel/feature/memo/MemoViewModel.kt
  feature/profile/create/build.gradle.kts
  feature/profile/create/src/commonMain/kotlin/com/whatever/caramel/feature/profile/create/ProfileCreateViewModel.kt
  feature/profile/create/src/commonMain/kotlin/com/whatever/caramel/feature/profile/create/di/Module.kt
  feature/profile/edit/build.gradle.kts
  feature/profile/edit/src/commonMain/kotlin/com/whatever/caramel/feature/profile/edit/ProfileEditViewModel.kt
  feature/setting/build.gradle.kts
  feature/setting/src/commonMain/kotlin/com/whatever/caramel/feature/setting/SettingViewModel.kt
  feature/splash/build.gradle.kts
  feature/splash/src/commonMain/kotlin/com/whatever/caramel/feature/splash/SplashViewModel.kt
Labels: ✨Feature

#240 [Fix] Slack Notifier - 이슈 종료 알림 메세지 출력 오류 수정
  .github/workflows/issue-closed.yml
Labels: 🛠Fix

#244 [QA] 메모 - 칩 스크롤 인터랙션
  core/designsystem/src/commonMain/kotlin/com/whatever/caramel/core/designsystem/animation/LazyListState.kt
  feature/memo/src/commonMain/kotlin/com/whatever/caramel/feature/memo/MemoScreen.kt
  feature/memo/src/commonMain/kotlin/com/whatever/caramel/feature/memo/MemoViewModel.kt
  feature/memo/src/commonMain/kotlin/com/whatever/caramel/feature/memo/mvi/MemoIntent.kt
  feature/memo/src/commonMain/kotlin/com/whatever/caramel/feature/memo/mvi/MemoState.kt
Labels: 🔃Refactor

#245 [QA] 캘린더 리스트 펼칠 때 버벅임
  feature/calendar/src/commonMain/kotlin/com/whatever/caramel/feature/calendar/CalendarScreen.kt
  feature/calendar/src/commonMain/kotlin/com/whatever/caramel/feature/calendar/component/bottomSheet/BottomSheetHandle.kt
  feature/calendar/src/commonMain/kotlin/com/whatever/caramel/feature/calendar/mvi/CalendarState.kt
Labels: 🛠Fix

#247 [QA] 홈, 컨텐츠 - 글자 수 카운팅 방식
  core/ui/src/commonMain/kotlin/com/whatever/caramel/core/ui/UiText.kt
  core/ui/src/commonMain/kotlin/com/whatever/caramel/core/ui/util/InputTextValidation.kt
  feature/content/create/src/commonMain/kotlin/com/whatever/caramel/feature/content/create/ContentCreateViewModel.kt
  feature/content/edit/src/commonMain/kotlin/com/whatever/caramel/feature/content/edit/ContentEditViewModel.kt
  feature/content/edit/src/commonMain/kotlin/com/whatever/caramel/feature/content/edit/mvi/ContentEditState.kt
  feature/home/src/commonMain/kotlin/com/whatever/caramel/feature/home/HomeRoute.kt
  feature/home/src/commonMain/kotlin/com/whatever/caramel/feature/home/HomeScreen.kt
  feature/home/src/commonMain/kotlin/com/whatever/caramel/feature/home/HomeViewModel.kt
  feature/home/src/commonMain/kotlin/com/whatever/caramel/feature/home/components/BottomSheet.kt
  feature/home/src/commonMain/kotlin/com/whatever/caramel/feature/home/mvi/HomeIntent.kt
  feature/home/src/commonMain/kotlin/com/whatever/caramel/feature/home/mvi/HomeSideEffect.kt
  feature/home/src/commonMain/kotlin/com/whatever/caramel/feature/home/mvi/HomeState.kt
Labels: 🔃Refactor

#248 [Feat] API 요청시 타임존 헤더 추가
  core/remote/src/androidMain/kotlin/com/whatever/caramel/core/remote/network/config/TimeZoneHeader.android.kt
  core/remote/src/commonMain/kotlin/com/whatever/caramel/core/remote/di/Module.kt
  core/remote/src/commonMain/kotlin/com/whatever/caramel/core/remote/network/config/TimeZoneHeader.kt
  core/remote/src/iosMain/kotlin/com/whatever/caramel/core/remote/network/config/TimeZoneHeader.ios.kt
Labels: ✨Feature

#253 [Fix] iOS - 정규식 문제 수정
  core/ui/src/commonMain/kotlin/com/whatever/caramel/core/ui/util/InputTextValidation.kt
  feature/home/src/commonMain/kotlin/com/whatever/caramel/feature/home/mvi/HomeState.kt
Labels: 🛠Fix

#256 [Fix] 컨텐츠 상세 - 날짜 아이콘 색상, 크기 변경
  core/designsystem/src/commonMain/composeResources/drawable/ic_calendar_18.xml
  core/designsystem/src/commonMain/kotlin/com/whatever/caramel/core/designsystem/foundations/Resources.kt
  feature/content/detail/src/commonMain/kotlin/com/whatever/caramel/feature/content/detail/ContentDetailScreen.kt
Labels: 🛠Fix

#258 [Fix] 설정 - 커플 시작일 API 타임존 헤더 중복 제거
  core/data/src/commonMain/kotlin/com/whatever/caramel/core/data/repository/CoupleRepositoryImpl.kt
  core/remote/src/commonMain/kotlin/com/whatever/caramel/core/remote/datasource/RemoteCoupleDataSource.kt
  core/remote/src/commonMain/kotlin/com/whatever/caramel/core/remote/datasource/RemoteCoupleDatsSourceImpl.kt
Labels: 🛠Fix

#259 [QA] 캘린더 BottomSheet를 누를 경우 isShowDatePicker를 false로 변경
  feature/calendar/src/commonMain/kotlin/com/whatever/caramel/feature/calendar/CalendarScreen.kt
  feature/calendar/src/commonMain/kotlin/com/whatever/caramel/feature/calendar/CalendarViewModel.kt
  feature/calendar/src/commonMain/kotlin/com/whatever/caramel/feature/calendar/component/bottomSheet/BottomSheetHandle.kt
  feature/calendar/src/commonMain/kotlin/com/whatever/caramel/feature/calendar/mvi/CalendarIntent.kt
Labels: 🛠Fix

#260 [FIX] 오늘의 일정에 제목이 없는 경우 내용으로 수정
  feature/home/src/commonMain/kotlin/com/whatever/caramel/feature/home/HomeViewModel.kt
Labels: 🛠Fix

#262 [Refactor] 깃액션 시크릿 키 변경으로 인한 키값 수정
  .github/workflows/add-pr-to-project.yml
Labels: 🔃Refactor

#263 [Feat] PR 리마인더 워크플로우 구현
  .github/workflows/pr-reminder.yml
Labels: ✨Feature

#269 [FEAT] 컨텐츠(일정, 메모)의 소유자 enum class 생성
  core/domain/src/commonMain/kotlin/com/whatever/caramel/core/domain/vo/content/ContentRole.kt
Labels: ✨Feature

#283 [Fix] PR 리마인더 슬랙 메세지 형식 오류 수정
  .github/workflows/pr-reminder.yml
Labels: 🛠Fix

#284 [Fix] PR 리마인더 gh 로그인 오류 수정
  .github/workflows/pr-reminder.yml
Labels: 🛠Fix

#281 [Fix] PR 리마인더 워크플로우 스케쥴링 시간 수정
  .github/workflows/pr-reminder.yml
Labels: 🛠Fix

#300 [Feat] 컨텐츠 생성 - 담당자 컴포넌트 구현
  core/designsystem/build.gradle.kts
  core/designsystem/src/commonMain/composeResources/values/strings.xml
  core/ui/src/commonMain/kotlin/com/whatever/caramel/core/ui/content/ContentRoleChipRow.kt
  feature/content/create/src/commonMain/kotlin/com/whatever/caramel/feature/content/create/ContentCreateScreen.kt
  feature/content/create/src/commonMain/kotlin/com/whatever/caramel/feature/content/create/ContentCreateViewModel.kt
  feature/content/create/src/commonMain/kotlin/com/whatever/caramel/feature/content/create/mvi/ContentCreateIntent.kt
  feature/content/create/src/commonMain/kotlin/com/whatever/caramel/feature/content/create/mvi/ContentCreateState.kt
Labels: ✨Feature

#307 [Feat] ContentRole 서버 DTO 추가
  core/data/src/commonMain/kotlin/com/whatever/caramel/core/data/repository/CalendarRepositoryImpl.kt
  core/data/src/commonMain/kotlin/com/whatever/caramel/core/data/repository/MemoRepositoryImpl.kt
  core/domain/src/commonMain/kotlin/com/whatever/caramel/core/domain/vo/content/ContentAssignee.kt
  core/remote/src/commonMain/kotlin/com/whatever/caramel/core/remote/dto/calendar/CalendarDetailResponse.kt
  core/remote/src/commonMain/kotlin/com/whatever/caramel/core/remote/dto/calendar/request/CreateScheduleRequest.kt
  core/remote/src/commonMain/kotlin/com/whatever/caramel/core/remote/dto/calendar/request/UpdateScheduleRequest.kt
  core/remote/src/commonMain/kotlin/com/whatever/caramel/core/remote/dto/memo/ContentAssigneeDto.kt
  core/remote/src/commonMain/kotlin/com/whatever/caramel/core/remote/dto/memo/request/CreateMemoRequest.kt
  core/remote/src/commonMain/kotlin/com/whatever/caramel/core/remote/dto/memo/request/UpdateMemoRequest.kt
  core/remote/src/commonMain/kotlin/com/whatever/caramel/core/remote/dto/memo/response/CursoredContentResponse.kt
  core/remote/src/commonMain/kotlin/com/whatever/caramel/core/remote/dto/memo/response/GetMemoResponse.kt
Labels: ✨Feature

#305 [Feat, Refactor] 홈 - State 코드 최적화 및 오늘의 일정 아이템에 일정 담당자 추가
  core/data/src/commonMain/kotlin/com/whatever/caramel/core/data/mapper/CalendarMapper.kt
  core/data/src/commonMain/kotlin/com/whatever/caramel/core/data/repository/CalendarRepositoryImpl.kt
  core/data/src/commonMain/kotlin/com/whatever/caramel/core/data/repository/MemoRepositoryImpl.kt
  core/domain/src/commonMain/kotlin/com/whatever/caramel/core/domain/entity/Todo.kt
  core/domain/src/commonMain/kotlin/com/whatever/caramel/core/domain/vo/content/ContentAssignee.kt
  core/remote/src/commonMain/kotlin/com/whatever/caramel/core/remote/dto/calendar/CalendarDetailResponse.kt
  core/remote/src/commonMain/kotlin/com/whatever/caramel/core/remote/dto/calendar/request/CreateScheduleRequest.kt
  core/remote/src/commonMain/kotlin/com/whatever/caramel/core/remote/dto/calendar/request/UpdateScheduleRequest.kt
  core/remote/src/commonMain/kotlin/com/whatever/caramel/core/remote/dto/memo/ContentAssigneeDto.kt
  core/remote/src/commonMain/kotlin/com/whatever/caramel/core/remote/dto/memo/request/CreateMemoRequest.kt
  core/remote/src/commonMain/kotlin/com/whatever/caramel/core/remote/dto/memo/request/UpdateMemoRequest.kt
  core/remote/src/commonMain/kotlin/com/whatever/caramel/core/remote/dto/memo/response/CursoredContentResponse.kt
  core/remote/src/commonMain/kotlin/com/whatever/caramel/core/remote/dto/memo/response/GetMemoResponse.kt
  feature/home/src/androidMain/kotlin/com/whatever/caramel/feature/home/HomeScreenPreviewData.kt
  feature/home/src/androidMain/kotlin/com/whatever/caramel/feature/home/QuizPreviewData.kt
  feature/home/src/commonMain/composeResources/values/strings.xml
  feature/home/src/commonMain/kotlin/com/whatever/caramel/feature/home/HomeScreen.kt
  feature/home/src/commonMain/kotlin/com/whatever/caramel/feature/home/HomeViewModel.kt
  feature/home/src/commonMain/kotlin/com/whatever/caramel/feature/home/components/quiz/BalanceGameResult.kt
  feature/home/src/commonMain/kotlin/com/whatever/caramel/feature/home/components/quiz/OptionButton.kt
  feature/home/src/commonMain/kotlin/com/whatever/caramel/feature/home/components/quiz/Quiz.kt
  feature/home/src/commonMain/kotlin/com/whatever/caramel/feature/home/components/todo/ContentAssigneeChip.kt
  feature/home/src/commonMain/kotlin/com/whatever/caramel/feature/home/components/todo/Todos.kt
  feature/home/src/commonMain/kotlin/com/whatever/caramel/feature/home/mvi/HomeIntent.kt
  feature/home/src/commonMain/kotlin/com/whatever/caramel/feature/home/mvi/HomeState.kt
Labels: ✨Feature, 🔃Refactor

#312 [Feat] 캘린더 - 일정 담당자 API 연동
  .github/workflows/pr-reminder.yml
  core/data/src/commonMain/kotlin/com/whatever/caramel/core/data/mapper/CalendarMapper.kt
  core/data/src/commonMain/kotlin/com/whatever/caramel/core/data/repository/CalendarRepositoryImpl.kt
  core/data/src/commonMain/kotlin/com/whatever/caramel/core/data/repository/MemoRepositoryImpl.kt
  core/domain/src/commonMain/kotlin/com/whatever/caramel/core/domain/entity/Todo.kt
  core/domain/src/commonMain/kotlin/com/whatever/caramel/core/domain/vo/content/ContentAssignee.kt
  core/remote/src/commonMain/kotlin/com/whatever/caramel/core/remote/dto/calendar/CalendarDetailResponse.kt
  core/remote/src/commonMain/kotlin/com/whatever/caramel/core/remote/dto/calendar/request/CreateScheduleRequest.kt
  core/remote/src/commonMain/kotlin/com/whatever/caramel/core/remote/dto/calendar/request/UpdateScheduleRequest.kt
  core/remote/src/commonMain/kotlin/com/whatever/caramel/core/remote/dto/memo/ContentAssigneeDto.kt
  core/remote/src/commonMain/kotlin/com/whatever/caramel/core/remote/dto/memo/request/CreateMemoRequest.kt
  core/remote/src/commonMain/kotlin/com/whatever/caramel/core/remote/dto/memo/request/UpdateMemoRequest.kt
  core/remote/src/commonMain/kotlin/com/whatever/caramel/core/remote/dto/memo/response/CursoredContentResponse.kt
  core/remote/src/commonMain/kotlin/com/whatever/caramel/core/remote/dto/memo/response/GetMemoResponse.kt
  feature/calendar/src/androidMain/kotlin/com/whatever/caramel/feature/calendar/component/CalendarBottomSheetPreviewData.kt
  feature/calendar/src/androidMain/kotlin/com/whatever/caramel/feature/calendar/component/CalendarScreenPreview.kt
  feature/calendar/src/androidMain/kotlin/com/whatever/caramel/feature/calendar/component/CalendarScreenPreviewData.kt
  feature/calendar/src/commonMain/kotlin/com/whatever/caramel/feature/calendar/CalendarScreen.kt
  feature/calendar/src/commonMain/kotlin/com/whatever/caramel/feature/calendar/component/bottomSheet/TodoList.kt
  feature/calendar/src/commonMain/kotlin/com/whatever/caramel/feature/calendar/component/calendar/Schedule.kt
Labels: ✨Feature

#311 [Feat] 컨텐츠 조회 - 일정 담당자 UI 구현
  core/data/src/commonMain/kotlin/com/whatever/caramel/core/data/mapper/CalendarMapper.kt
  core/data/src/commonMain/kotlin/com/whatever/caramel/core/data/mapper/ContentMapper.kt
  core/designsystem/src/commonMain/composeResources/drawable/ic_tag_18.xml
  core/designsystem/src/commonMain/kotlin/com/whatever/caramel/core/designsystem/foundations/Resources.kt
  core/designsystem/src/commonMain/kotlin/com/whatever/caramel/core/designsystem/themes/CaramelColor.kt
  core/domain/src/commonMain/kotlin/com/whatever/caramel/core/domain/entity/Memo.kt
  core/domain/src/commonMain/kotlin/com/whatever/caramel/core/domain/vo/calendar/ScheduleDetail.kt
  feature/content/detail/src/androidMain/kotlin/com/whatever/caramel/feature/content/detail/ContentDetailPreview.kt
  feature/content/detail/src/androidMain/kotlin/com/whatever/caramel/feature/content/detail/ContentDetailPreviewParameter.kt
  feature/content/detail/src/commonMain/composeResources/values/strings.xml
  feature/content/detail/src/commonMain/kotlin/com/whatever/caramel/feature/content/detail/ContentDetailScreen.kt
  feature/content/detail/src/commonMain/kotlin/com/whatever/caramel/feature/content/detail/mvi/ContentDetailState.kt
  feature/memo/src/androidMain/kotlin/com/whatever/caramel/feature/memo/component/MemoScreenPreviewProvider.kt
Labels: ✨Feature

#310 [Feat] 컨텐츠 생성 - 담당자 선택 기능 추가
  core/data/src/commonMain/kotlin/com/whatever/caramel/core/data/repository/CalendarRepositoryImpl.kt
  core/data/src/commonMain/kotlin/com/whatever/caramel/core/data/repository/MemoRepositoryImpl.kt
  core/designsystem/build.gradle.kts
  core/designsystem/src/commonMain/composeResources/values/strings.xml
  core/domain/src/commonMain/kotlin/com/whatever/caramel/core/domain/usecase/memo/CreateContentUseCase.kt
  core/domain/src/commonMain/kotlin/com/whatever/caramel/core/domain/vo/calendar/ScheduleParameter.kt
  core/domain/src/commonMain/kotlin/com/whatever/caramel/core/domain/vo/memo/MemoParameter.kt
  core/remote/src/commonMain/kotlin/com/whatever/caramel/core/remote/dto/calendar/CalendarDetailResponse.kt
  core/ui/src/commonMain/kotlin/com/whatever/caramel/core/ui/content/ContentRoleChipRow.kt
  core/ui/src/commonMain/kotlin/com/whatever/caramel/core/ui/content/SelectableTagChipRow.kt
  feature/content/create/src/commonMain/kotlin/com/whatever/caramel/feature/content/create/ContentCreateScreen.kt
  feature/content/create/src/commonMain/kotlin/com/whatever/caramel/feature/content/create/ContentCreateViewModel.kt
  feature/content/create/src/commonMain/kotlin/com/whatever/caramel/feature/content/create/mvi/ContentCreateIntent.kt
  feature/content/create/src/commonMain/kotlin/com/whatever/caramel/feature/content/create/mvi/ContentCreateState.kt
Labels: ✨Feature

#319 [Feat] 컨텐츠 조회 - 일정 담당자 API 연동
  core/data/src/commonMain/kotlin/com/whatever/caramel/core/data/mapper/CalendarMapper.kt
  core/data/src/commonMain/kotlin/com/whatever/caramel/core/data/mapper/ContentMapper.kt
  core/domain/src/commonMain/kotlin/com/whatever/caramel/core/domain/entity/Memo.kt
  feature/content/detail/src/commonMain/kotlin/com/whatever/caramel/feature/content/detail/mvi/ContentDetailState.kt
  feature/memo/src/androidMain/kotlin/com/whatever/caramel/feature/memo/component/MemoScreenPreviewProvider.kt
Labels: ✨Feature

#314 [Fix] 컨텐츠 - 본문 줄바꿈 버그 수정
  core/data/src/commonMain/kotlin/com/whatever/caramel/core/data/mapper/CalendarMapper.kt
  core/domain/src/commonMain/kotlin/com/whatever/caramel/core/domain/exception/code/ContentErrorCode.kt
  core/domain/src/commonMain/kotlin/com/whatever/caramel/core/domain/validator/ContentValidator.kt
  core/domain/src/commonMain/kotlin/com/whatever/caramel/core/domain/validator/util/CodePointCount.kt
  core/ui/src/commonMain/kotlin/com/whatever/caramel/core/ui/util/InputTextValidation.kt
  feature/content/create/src/commonMain/kotlin/com/whatever/caramel/feature/content/create/ContentCreateViewModel.kt
  feature/content/create/src/commonMain/kotlin/com/whatever/caramel/feature/content/create/mvi/ContentCreateState.kt
  feature/content/edit/src/commonMain/kotlin/com/whatever/caramel/feature/content/edit/ContentEditViewModel.kt
  feature/content/edit/src/commonMain/kotlin/com/whatever/caramel/feature/content/edit/mvi/ContentEditState.kt
  feature/home/src/commonMain/kotlin/com/whatever/caramel/feature/home/HomeViewModel.kt
  feature/home/src/commonMain/kotlin/com/whatever/caramel/feature/home/mvi/HomeState.kt
Labels: 🛠Fix

#315 [Feat] 메모 리스트 - 메모에 일정 담당자 표시
  core/data/src/commonMain/kotlin/com/whatever/caramel/core/data/mapper/ContentMapper.kt
  core/domain/src/commonMain/kotlin/com/whatever/caramel/core/domain/entity/Memo.kt
  feature/memo/src/androidMain/kotlin/com/whatever/caramel/feature/memo/component/MemoScreenPreviewProvider.kt
  feature/memo/src/commonMain/composeResources/values/strings.xml
  feature/memo/src/commonMain/kotlin/com/whatever/caramel/feature/memo/MemoScreen.kt
  feature/memo/src/commonMain/kotlin/com/whatever/caramel/feature/memo/MemoViewModel.kt
  feature/memo/src/commonMain/kotlin/com/whatever/caramel/feature/memo/component/MemoItem.kt
  feature/memo/src/commonMain/kotlin/com/whatever/caramel/feature/memo/component/TagItem.kt
  feature/memo/src/commonMain/kotlin/com/whatever/caramel/feature/memo/model/MemoUiModel.kt
  feature/memo/src/commonMain/kotlin/com/whatever/caramel/feature/memo/mvi/MemoIntent.kt
  feature/memo/src/commonMain/kotlin/com/whatever/caramel/feature/memo/mvi/MemoState.kt
Labels: ✨Feature

#325 [Fix] Fastlane Dev 서버로 배포
  app-ios/iosApp.xcodeproj/project.pbxproj
  app-ios/iosApp/Info.plist
  fastlane/Fastfile
  fastlane/android-release-notes.txt
  fastlane/ios-release-notes.txt
  gradle/libs.versions.toml
Labels: 🛠Fix

#327 [Fix] Fastlane build type 변경
  app-ios/iosApp.xcodeproj/project.pbxproj
  app-ios/iosApp/Info.plist
  core/remote/build.gradle.kts
  core/remote/src/androidMain/kotlin/com/whatever/caramel/core/remote/network/config/NetworkConfig.kt
  core/remote/src/commonMain/kotlin/com/whatever/caramel/core/remote/di/Module.kt
  core/remote/src/commonMain/kotlin/com/whatever/caramel/core/remote/di/qualifier/NetworkClientQualifier.kt
  core/remote/src/commonMain/kotlin/com/whatever/caramel/core/remote/network/config/NetworkConfig.kt
  core/remote/src/iosMain/kotlin/com/whatever/caramel/core/remote/network/config/NetworkConfig.kt
  fastlane/Fastfile
  fastlane/android-release-notes.txt
  fastlane/ios-release-notes.txt
  gradle/libs.versions.toml
Labels: 🛠Fix

#330 [QA] 메모 리스트 UI 수정
  feature/memo/src/commonMain/kotlin/com/whatever/caramel/feature/memo/component/MemoItem.kt
Labels: 🛠Fix
